---
version: "3.3"
services:

  # prometheus metrics
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    command:
      - --path.rootfs=/host
    network_mode: host
    pid: host
    ports:
      - 9100:9100 # mapping port to 7100 for some reason did not work, gets mapped in Vagrantfile
    volumes:
      - /:/host:ro,rslave
      - /etc/timezone:/etc/timezone:ro

  # prometheus metrics
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    expose:
      - 7101
    ports:
      - 7101:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  # Mange containers
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer
    command: -H unix:///var/run/docker.sock --admin-password-file /tmp/portainer_password
    restart: always
    ports:
      - 7990:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
      - ./assets/portainer.passwd:/tmp/portainer_password
      - /etc/timezone:/etc/timezone:ro

volumes:
  portainer_data:
